version: '3'
services:
  mysql:
    image: mysql:5.7.29
    container_name: db-mysql
    restart: unless-stopped
    ports:
    - 3307:3306
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=docker
